# Generated by Django 5.2.4 on 2025-08-18 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 16, 5, 20, 713341), verbose_name='fecha_creacion'),
        ),
    ]
